language: python
sudo: required
dist: trusty
python:
    - "2.7"
before_install:
    - "export CHROMEDRIVER_DIR=~/chromedriver"
    - "export PATH=$CHROMEDRIVER_DIR:$PATH"
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "wget -q --continue -P $CHROMEDRIVER_DIR 'http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip'"
    - "unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR"
    - "sh install_test_deps.sh"
    - "pip uninstall -y xblock-drag-and-drop-v2"
    - "python setup.py sdist"
    - "pip install dist/xblock-drag-and-drop-v2-2.0.8.tar.gz"
script:
    - pep8 drag_and_drop_v2 tests --max-line-length=120
    - pylint drag_and_drop_v2
    - pylint tests --rcfile=tests/pylintrc
    - python run_tests.py
notifications:
    email: false
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable=52.0.2743.116-1
